version: "3"

services:
  drzl-pg:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${VITE_POSTGRES_PASSWORD}
      POSTGRES_USER: ${VITE_POSTGRES_USER}
      POSTGRES_DB: ${VITE_POSTGRES_DB}

    volumes:
      - drzl-pg-data:/var/lib/postgres

    networks:
      - auths-network

  drzl-redis:
    image: redis:latest

    volumes:
      - drzl-redis-data:/data

    networks:
      - auths-network

  app:
    image: myimage:l3.9.0
    profiles:
      - webapp
    environment:
      POSTGRES_PASSWORD: ${VITE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${VITE_POSTGRES_DB}
    env_file:
      - ./.env

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5
    depends_on:
      - drzl-pg
      - drzl-redis
    networks:
      - auths-network

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - auths-network
    depends_on:
      - app
      - drzl-pg
      - drzl-redis
networks:
  auths-network:
    driver: bridge
volumes:
  drzl-pg-data:
  drzl-redis-data:
  node_modules:
